"""JWT token generation and validation for platform↔app authentication.

Apps receive a JWT at startup (generated by AppManager), validate it on
incoming requests, and can request renewal before expiry.  Uses PyJWT
HS256 with the platform's existing secret key infrastructure.
"""

import hashlib
import hmac
import logging
from datetime import datetime, timedelta, timezone

import jwt

logger = logging.getLogger(__name__)


def get_secret() -> str:
    """Return the platform secret key for JWT signing.

    Delegates to the centralised key resolver in ``app.auth.tokens``.
    """
    from app.auth.tokens import _get_secret_key

    return _get_secret_key()


def get_app_secret(app_id: str) -> str:
    """Derive a per-app HMAC signing key from the platform secret.

    Each app gets a unique key so that a compromised app token cannot
    be used to forge tokens for other apps.

    Args:
        app_id: Unique app identifier used as the HMAC message.

    Returns:
        Hex-encoded HMAC-SHA256 digest, suitable for use as a JWT secret.
    """
    platform_key = get_secret()
    return hmac.new(
        platform_key.encode(), app_id.encode(), hashlib.sha256
    ).hexdigest()


def generate_app_token(
    app_id: str,
    permissions: dict,
    secret: str,
    ttl_seconds: int = 3600,
) -> str:
    """Generate an HS256 JWT for an app subprocess.

    Args:
        app_id: Unique app identifier (used as ``sub`` claim prefix).
        permissions: Permission map included verbatim in the token.
        secret: HMAC secret for signing.
        ttl_seconds: Token lifetime in seconds (default 1 hour).

    Returns:
        Encoded JWT string.
    """
    now = datetime.now(timezone.utc)
    claims = {
        "sub": f"app:{app_id}",
        "permissions": permissions,
        "iat": now,
        "exp": now + timedelta(seconds=ttl_seconds),
    }
    token = jwt.encode(claims, secret, algorithm="HS256")
    logger.debug(
        "app token generated for %s, expires %s",
        app_id,
        claims["exp"].isoformat(),
    )
    return token


def validate_app_token(
    token: str,
    secret: str,
    grace_seconds: int = 0,
) -> dict | None:
    """Decode and validate an app JWT.

    Args:
        token: Encoded JWT string.
        secret: Expected HMAC secret.
        grace_seconds: If > 0, accept tokens that expired up to this many
            seconds ago (used for token-renewal flow).

    Returns:
        Decoded claims dict on success, ``None`` on any validation failure.
    """
    try:
        claims = jwt.decode(token, secret, algorithms=["HS256"])
        logger.debug("app token validated, sub=%s", claims.get("sub"))
        return claims
    except jwt.ExpiredSignatureError:
        if grace_seconds > 0:
            return _validate_with_grace(token, secret, grace_seconds)
        logger.warning("app token expired (no grace)")
        return None
    except jwt.InvalidTokenError as exc:
        logger.warning("app token invalid: %s", type(exc).__name__)
        return None


def _validate_with_grace(
    token: str,
    secret: str,
    grace_seconds: int,
) -> dict | None:
    """Accept a token that expired within the grace window.

    Decodes without ``exp`` verification, then manually checks that
    ``exp + grace_seconds >= now``.
    """
    try:
        claims = jwt.decode(
            token,
            secret,
            algorithms=["HS256"],
            options={"verify_exp": False},
        )
        exp = claims.get("exp")
        if exp is None:
            logger.debug("app token has no exp claim, rejecting in grace path")
            return None

        exp_dt = datetime.fromtimestamp(exp, tz=timezone.utc)
        now = datetime.now(timezone.utc)

        if exp_dt + timedelta(seconds=grace_seconds) >= now:
            logger.debug(
                "app token accepted within grace window, sub=%s",
                claims.get("sub"),
            )
            return claims

        logger.debug(
            "app token expired beyond grace window (%s past expiry)",
            now - exp_dt,
        )
        return None
    except jwt.InvalidTokenError as exc:
        logger.warning("app token invalid in grace path: %s", type(exc).__name__)
        return None
